project:
  type: book
  output-dir: _book
  resources:
    - slides
    - images

book:
  title: "Relatório Metodológico"
  favicon: "images/favicon.ico"
  subtitle: "GTFShift Edição TML: Ferramenta de priorização de corredores bus e análise de operações"
  author: "U-Shift Lab, Instituto Superior Técnico"
  date: today
  date-format: "MMMM YYYY"
  chapters:
    - index.qmd
    - part: "**Dados**"
      chapters:
        - dados_fontes.qmd
        - dados_preparacao.qmd
    - part: "**Metodologia e visualização**"
      chapters:
        - metodologia.qmd
        - metodologia_indice_perturbacao.qmd
        - metodologia_priorizacao.qmd
        - metodologia_corredores_bus.qmd
        - metodologia_frequencia.qmd
        - metodologia_nr_vias.qmd
        - metodologia_velocidade_rt.qmd
        - metodologia_velocidade_comercial.qmd
        - metodologia_procura.qmd
        - resultados.qmd
    - part: "**Painel interativo**"
      chapters:
        - dashboard.qmd
        - dashboard_infraestrutura.qmd
        - dashboard_linhas.qmd
        - dashboard_viagens.qmd
    - conclusao.qmd
    - about.qmd
    - references.qmd
  sidebar:
    tools:
    - icon: github
      href: https://github.com/U-Shift/GTFShift-TML/
      text: "Repositório GitHub"
      target: _blank
    - icon: map-fill
      href: https://ushift.pt/apps/gtfshift-tml
      text: "Painel interativo"
      target: _blank
  page-footer:
    left: "&copy; 2026, U-Shift, CERIS, Instituto Superior Técnico, University of Lisbon"
    right: "September 2026"
    
bibliography: references.bib

lang: pt-pt

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    toc: true
    number-sections: true
    echo: false
    code-fold: true
    lightbox: true # abrir imagens popup
    css: "styles/global.css"
    include-after-body: 
      text: |
        <script src="styles/global.js"></script>

google-scholar: true