project:
  type: book
  output-dir: _book
  resources:
    - slides
    - images

book:
  title: "Relatório Metodológico"
  favicon: "images/favicon.ico"
  subtitle: "GTFShift Edição TML: Ferramenta de priorização de corredores bus e análise de operações"
  author: "U-Shift Lab, Instituto Superior Técnico"
  date: today
  date-format: "MMMM YYYY"
  chapters:
    - index.qmd
    - part: "**Dados**"
      chapters:
        - dados_fontes.qmd
        - dados_preparacao.qmd
    - part: "**Metodologia e visualização**"
      chapters:
        - metodologia.qmd
        - metodologia_indice_perturbacao.qmd
        - metodologia_priorizacao.qmd
        # - metodologia_frequencia.qmd
        # - metodologia_faixas_rodagem.qmd
        # - metodologia_faixas_estacionamento.qmd
        # - metodologia_faixas_bus.qmd
        # - metodologia_velocidade_rt.qmd
        # - metodologia_procura.qmd
        # - metodologia_paragens_terminais.qmd
        # - resultados.qmd
    # - part: "**Dashboard**"
    #  chapters:
    #    - dashboard.qmd
    - references.qmd
  sidebar:
    tools:
    - icon: github
      href: https://github.com/U-Shift/GTFShift-DI/
      text: "GitHub Repository"
      target: _blank
    - icon: map-fill
      href: https://ushift.pt/apps/gtfshift-tml
      text: "Interactive Dashboard"
      target: _blank
  page-footer:
    left: "&copy; 2026, U-Shift, CERIS, Instituto Superior Técnico, University of Lisbon"
    right: "September 2026"
    
bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    toc: true
    number-sections: true
    echo: false
    code-fold: true
    lightbox: true # abrir imagens popup
    css: "styles/global.css"
    include-after-body: 
      text: |
        <script src="styles/global.js"></script>

google-scholar: true