# Corredores *bus* existentes {#sec-corredores-bus}

Esta camada permite visualizar os segmentos de via da rede de transporte público onde já existe um corredor *bus* dedicado, de acordo com a base de dados do OSM.

## Identificação dos corredores *bus*

A existência de um corredor *bus* num segmento é determinada durante a execução de [`GTFShift::prioritise_lanes()`](https://u-shift.github.io/GTFShift/reference/prioritise_lanes.html){target=blank}, através da análise das etiquetas dos segmentos do OSM percorridos pelos serviços de transporte público. Em alternativa, pode ser utilizado o método [`GTFShift::osm_bus_lanes()`](https://u-shift.github.io/GTFShift/reference/osm_bus_lanes.html){target=blank}. As etiquetas OSM relevantes são:

| *Tag* OSM | Descrição |
|---|---|
| `psv:lanes` | Identifica corredor *bus* |
| `bus:lanes` | Identifica corredor *bus* |
| `lanes:psv` | Explicita número de vias com corredor *bus* |
| `lanes:bus` | Explicita número de vias com corredor *bus* |

O resultado é o campo booleano, que indica se o segmento possui atualmente um corredor *bus*.

A qualidade desta informação depende do nível de atualização do OpenStreetMap para a região em análise. Recomenda-se verificar e atualizar as etiquetas do OSM antes de executar a análise, para garantir que os corredores *bus* extraídos refletem a realidade.

## Visualização

Todos os segmentos com corredor *bus* são visualizados em <span style="color: #3bc1a8;">__Verde__</span>, independentemente dos outros atributos. A camada mostra exclusivamente corredores *bus* existentes, sem qualquer filtragem por frequência ou outros critérios.


## Interpretação

Esta camada serve como referência espacial para compreender a distribuição atual da infraestrutura de corredores *bus* na rede, complementando a camada da priorização. 

Através da sua análise é possível ao utilizador verificar a continuidade da rede, um fator que a literatura considera como multiplicador no que toca à eficiência operacional. @truong_exploring_2015 verificou uma relação linear na melhoria da performance operacional com a agregação de corredores *bus*.
